export const markers = [
    {
        coordinate: {
            latitude: 22.6293867,
            longitude: 88.4354486,
        },
        id: '1',
        hotelImage: require('../assets/images/hotel/hotel_1.jpg'),
        hotelName: 'Hotel des Comedies Paris',
        hotelAddress: '8 Rue d\' Hauteville,75010 Paris,France',
        hotelAbout: 'Upmarket hotels with an airy lounger/bar',
        amount: 70,
        rating: 5.0,
    },
    {
        coordinate: {
            latitude: 22.6345648,
            longitude: 88.4377279,
        },
        id: '2',
        hotelImage: require('../assets/images/hotel/hotel_2.jpg'),
        hotelName: 'Paris France Hotel',
        hotelAddress: '72 Rue de Turbigo, 75003 Paris, France',
        amount: 50,
        rating: 4.0,
    },
    {
        coordinate: {
            latitude: 22.6281662,
            longitude: 88.4410113,
        },
        id: '3',
        hotelImage: require('../assets/images/hotel/hotel_3.jpg'),
        hotelName: 'Pullman Paris Tour Eiffel',
        hotelAddress: '18 Avenue Suffren,22 Rue Jean Rey Entree Au,75015',
        hotelAbout: 'High-end lodging with Eiffel Tower views',
        amount: 60,
        rating: 5.0,
    },
    {
        coordinate: {
            latitude: 22.624251190376572,
            longitude: 88.43461990356447,
        },
        id: '4',
        hotelImage: require('../assets/images/hotel/hotel_4.jpg'),
        hotelName: 'Hotel Darcet',
        hotelAddress: '4 Rue Darcet, 75017 Paris, France',
        hotelAbout: 'Simple rooms with free Wi-Fi, plus a bar',
        amount: 55,
        rating: 4.0,
    },
    {
        coordinate: {
            latitude: 22.6292757,
            longitude: 88.444781,
        },
        id: '5',
        hotelImage: require('../assets/images/hotel/hotel_5.jpg'),
        hotelName: 'Novotel Tour Eiffel Hotel',
        hotelAddress: '61 Quai de Grenelle, 75015 Paris, France',
        hotelAbout: 'Modern lodging with dining & free Wi-Fi',
        amount: 35,
        rating: 3.0,
    },
    {
        coordinate: {
            latitude: 22.6304900,
            longitude: 88.4377956,
        },
        id: '6',
        hotelImage: require('../assets/images/hotel/hotel_6.jpg'),
        hotelName: 'Shangri-La Hotel',
        hotelAddress: '10 Avenue diena,75116 Paris,France',
        hotelAbout: 'Posh hotel with acclaimed dining & a spa',
        amount: 80,
        rating: 5.0,
    },
    {
        coordinate: {
            latitude: 22.6287471,
            longitude: 88.4392547,
        },
        id: '7',
        hotelImage: require('../assets/images/hotel/hotel_7.jpg'),
        hotelName: 'Le Bristrol Paris',
        hotelAddress: '112 Rue du Faubourf Saint-Honore, 75008 Paris, France',
        hotelAbout: 'Posh hotel with a spa & fine dining',
        amount: 80,
        rating: 5.0,
    },
    {
        coordinate: {
            latitude: 22.6224884,
            longitude: 88.4332895,
        },
        id: '8',
        hotelImage: require('../assets/images/hotel/hotel_8.jpg'),
        hotelName: 'Castille Paris',
        hotelAddress: '33-37 Rue Cambon, 75001 Paris, France',
        hotelAbout: 'Posh rooms & suites, plus elegant dining',
        amount: 80,
        rating: 4.0,
    },
];