export const recommendedsList = [
    {
        id: '1',
        hotelImage: require('../assets/images/hotel/hostel1.jpg'),
        hotelName: 'deluxe-room-at-da-wilderness',
        rating: 5.0,
        place: 'Ndeje',
        amount: 70,
    },
    {
        id: '2',
        hotelImage: require('../assets/images/hotel/hostel2.jpg'),
        hotelName: 'EA Hostel',
        rating: 4.0,
        place: 'Ndeje',
        amount: 50,
    },
    // {
    //     id: '3',
    //     hotelImage: require('../assets/images/hotel/hotel_3.jpg'),
    //     hotelName: 'Paris France Hotel',
    //     rating: 5.0,
    //     place: 'France',
    //     amount: 60,
    // },
    // {
    //     id: '4',
    //     hotelImage: require('../assets/images/hotel/hotel_4.jpg'),
    //     hotelName: 'Hotel My Home',
    //     rating: 4.0,
    //     place: 'Vietnam',
    //     amount: 55,
    // },
    // {
    //     id: '5',
    //     hotelImage: require('../assets/images/hotel/hotel_5.jpg'),
    //     hotelName: 'Hotel Darcet',
    //     rating: 3.0,
    //     place: 'Paris',
    //     amount: 35,
    // },
    // {
    //     id: '6',
    //     hotelImage: require('../assets/images/hotel/hotel_6.jpg'),
    //     hotelName: 'Novotel Paris Les Halles',
    //     rating: 5.0,
    //     place: 'Paris',
    //     amount: 80,
    // },
];
